---
# Sample cloud configuration

###########################################
## DataSource Configuration
###########################################

jdbc:
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/cloudine?useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull
  username: root
  password:
  min:
    pool: 3
  max:
    pool: 30


##########################################
## JavaMail Configuration
###########################################

mail:
  host: smtp.gmail.com
  username: flamingo.workflow@gmail.com
  password: princoprinco9
  port: 587
  smtp:
    auth: true
  smtp:
    starttls:
      enable: true
  from:
    address: flamingo.workflow@gmail.com
    name: uEngine
  html: false
  contacts:
    address: support@uengine.org