management:
  security:
    enabled: false

security:
  basic:
    enabled: false
  ignored: /**
  password:
    encoder:
      secret1: Bar12345Bar12345
      secret2: ThisIsASecretKet

spring:
  security:
    enabled: false
  data:
    rest:
      basePath: /api/v1

server:
  port: 8080
  servletPath: /

# ========================================
#  IAM 시스템 Configuration
# ========================================

iam:
# 어드민 정보
  admin:
    username: admin
    password: admin
  jwt:
    # jwt 암호화 키
    key: my-jwt-encrypt-key-my-jwt-encrypt-key

    # jwt 발급자
    issuer: ${spring.application.name}

    # 기한 만료된 리프레쉬 토큰 삭제 체크 인터벌
    oldRefreshTokenTimeout: 60

    # 메타데이터 암호화 키
    metadata-encoder-secret1: Bar12345Bar12345
    metadata-encoder-secret2: ThisIsASecretKet

    # 암호화 할 메타데이터 필드.
    secure-metadata-fields:
      - "$.gitlabToken"

# 시스템 이메일 정보 (옵셔널)
  mail:
    host: @iam.mail.host@
    username: @iam.mail.username@
    password: "!gosu23546"
    #password: @iam.mail.password@
    port: @iam.mail.port@
    smtp-auth: @iam.mail.smtp-auth@
    smtp-starttls-enable: @iam.mail.smtp-starttls-enable@
    from-address: @iam.mail.from-address@
    from-name: @iam.mail.from-name@

  billing:
    url: "http://billing.pas-mini.io"
    authentication: "Basic YmlsbGluZ0B1ZW5naW5lLm9yZzoxODkyNXVuZw=="
    organization: "562980b6-9ad6-4257-b276-a38825522f69"
    account-sync: true
    account-sync-body:
      name: "$.name" #required
      email: "$.email" #required
      billCycleDayLocal: 0 #required
      currency: "KRW" #required
      locale: "ko_KR" #required
      parentAccountId: null
      isPaymentDelegatedToParent: false
      timeZone: "UTC"
      address1: "$.address1"
      address2: "$.address2"
      postalCode: "$.postalCode"
      company: "$.company"
      city: "$.city"
      state: "$.state"
      country: "KR"
      phone: "$.phone"
      notes: "$.notes"
      isNotifiedForInvoices: true

# =============================================
#  스코프 - 주로 백엔드 서비스에 해당됩니다.
# =============================================
scopes:
  - name: cloud-server
    description: 클라우드 서버 접근을 허용합니다.
  - name: billing
    description: 빌링 서비스의 접근을 허용합니다.
  - name: bpm
    description: bpm 서비스를 사용합니다.
  - name: course-mgmt
    description: course-mgmt 서비스를 사용합니다.
  - name: class-mgmt
    description: class-mgmt 서비스를 사용합니다.


# =============================================
#  클라이언트 - 주로 프론트 엔드 어플리케이션에 해당됩니다.
# =============================================
clients:
  - name: uEngine-cloud
    description: uEngine cloud Application
    clientKey: @iam.client-key@
    clientSecret: @iam.client-secret@

    # 토큰 발급시 요청할 수 있는 스코프 목록.
    enable-scopes: cloud-server,bpm,billing,course-mgmt,class-mgmt

    # 유저 스코프 체크. 유저 metadata 의 scopes 를 검사한다.
    # true: 요청받은 스코프를 모두 가지고 있어야 한다.
    # false: 요청받은 스코프 중 일부만 가지고 있으면 된다. (default)
    user-scope-check-all: false

    # client-key,client-secret 헤더로 Rest api 를 호출할 수 있는 권한.
    # 회원 가입,사용자 정보 수정등의 rest api 를 호출할 수 있다.
    # 서드파티 어플리케이션은 권한을 주면 안되고, 오피셜 어플리케이션은 권한을 가지는것을 추천.
    access-rest-enable: true

    # 클라이언트 활성화 여부
    activeClient: true

    # 지원하는 그런트 타입.
    authorizedGrantTypes: code,implicit,password,credentials

    # code,implicit 방식의 로그인일 때 리다이렉트 되는 주소.
    webServerRedirectUri: http://cloud.pas-mini.io#login-redirect

    # 리프레쉬 토큰 발급.
    refreshTokenValidity: true

    # 만기 토큰 자동 삭제.
    autoDeletionToken: true

    # JWT 토큰 콘텍스트에 포함될 정보 : clientKey,scopes,type,refreshToken,userName,user | ALL
    requiredContext: clientKey,scopes,type,refreshToken,userName,user

    # JWT 토큰 알고리즘: HS256 or RS256
    jwtAlgorithm: HS256

    # code 인증 방식의 유지시간.
    codeLifetime: 36000

    # 리프레쉬 토큰 유효시간
    refreshTokenLifetime: 2592000

    # 어세스 토큰 유효시간
    accessTokenLifetime: @iam.access-token-lifetime@

    # 사용자 알림 메일 발송 SIGN_UP,SIGNED_UP,FORGOT_PASSWORD,PASSWORD_CHANGED | ALL
    notification: ALL

---
# =============================================
#  레파지토리 - 데이터 베이스 정보입니다.
# =============================================

spring:
  profiles: local
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
  datasource:
      url: jdbc:mysql://@host.db@:10002/@db.database@
      username: root
      password: @db.password@

vcap:
  services:
    db:
      external: "@host.db@:10002"
      internal: "marathon-lb-internal.marathon.mesos:10002"
    iam:
      external: "@host.iam@"
      internal: "marathon-lb-internal.marathon.mesos:10003"
    uengine-cloud-config:
      external: "@server.public.public@:10000"
      internal: "marathon-lb-internal.marathon.mesos:10000"
    eureka-server:
      external: "@host.eureka-server@"
      internal: "marathon-lb-internal.marathon.mesos:10001"
    uengine-cloud-server:
      external: "@host.cloud-server@"
      internal: "marathon-lb-internal.marathon.mesos:10005"
    uengine-cloud-ui:
      external: "@host.cloud-ui@"
      internal: "marathon-lb-internal.marathon.mesos:10006"

# ======================
#  Eureka Configuration
# ======================

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    statusPageUrlPath: ${server.servletPath}info
    healthCheckUrlPath: ${server.servletPath}health
    metadataMap:
        deployment: local
        profile: local

---
spring:
  profiles: docker
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
  datasource:
    url: jdbc:mysql://${vcap.services.db.internal}/@db.database@
    username: root
    password: @db.password@

# ======================
#  Eureka Configuration
# ======================

eureka:
  client:
    serviceUrl:
      defaultZone: http://${vcap.services.eureka-server.internal}/eureka/
    healthcheck:
      enabled: true
  instance:
    hostname: ${HOST}
    nonSecurePort: ${PORT}
    preferIpAddress: false
    statusPageUrl: http://${eureka.instance.hostname}:${eureka.instance.nonSecurePort}/info
    healthCheckUrl: http://${eureka.instance.hostname}:${eureka.instance.nonSecurePort}/health
    homePageUrl: http://${eureka.instance.hostname}:${eureka.instance.nonSecurePort}/
    instanceId: ${HOST}:${spring.application.name}:${PORT}
    metadataMap:
        project: ${CI_PROJECT_NAME}
        commitSha: ${CI_COMMIT_SHA}
        image: ${MARATHON_APP_DOCKER_IMAGE}
        deployment: ${DEPLOYMENT}
        profile: ${PROFILE}