server.public.master: 52.79.125.242
server.public.public: 52.79.51.79

db.ip: 172.31.6.35
db.database: uengine
db.password: my-secret-pw

host.default: pas-mini.io
host.registry.package: sppark
host.registry.private: gitlab.pas-mini.io:5000
host.registry.public: gitlab.pas-mini.io:5000
host.db: db.pas-mini.io
host.gitlab: gitlab.pas-mini.io
host.iam: iam.pas-mini.io
host.config: 172.31.5.136:10000
host.eureka-server: eureka-server.pas-mini.io
host.cloud-server: cloud-server.pas-mini.io
host.cloud-ui: cloud.pas-mini.io

iam.port: 80
iam.client-key: my-client-key
iam.client-secret: my-client-secret
iam.admin.username: admin
iam.admin.password: admin
iam.access-token-lifetime: 7200
iam.mail.host: smtp.gmail.com
iam.mail.username: sppark@uengine.org
iam.mail.password: !gosu23546
iam.mail.port: 587
iam.mail.smtp-auth: true
iam.mail.smtp-starttls-enable: true
iam.mail.from-address: sppark@uengine.org
iam.mail.from-name: uengine

dcos.token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiJkYXJrZ29kYXJrZ29AZ21haWwuY29tIiwiZXhwIjozMTI1NTU5MDY0MzkuODk0MX0.aHgH_M-g-n-WlnPg_CorMGYEprULPSeUTIGu3GyZQ-U

gitlab.root.username: root
gitlab.root.password: adminadmin
gitlab.root.token: -arWnfRY7S4h6oyRthNy
gitlab.config-repo.projectId: 47
gitlab.config-repo.deployment-path: /deployment
gitlab.config-repo.template-path: /template

nexus.ip: 172.31.10.202
nexus.username: admin
nexus.password: admin123
nexus.public: http://nexus.pas-mini.io/nexus/content/groups/public/
nexus.release: http://nexus.pas-mini.io/nexus/content/repositories/releases/
nexus.snapshot: http://nexus.pas-mini.io/nexus/content/repositories/snapshots/









