# SSH and Resolve.conf part
cluster_name: uEngine
ansible_user: centos
ansible_ssh_private_key_file: /home/centos/dcos-key.pem
ssh_port: 22
resolvers:
- 121.88.255.50
- 121.88.255.49
dns_search:

# Server list part
server:
  private:
    bootstrap: 192.168.0.19
    gitlab: 192.168.0.31
    ci:
    public: 192.168.0.11

    master:
      master1: 192.168.0.8
      master2: 192.168.0.9
      master3: 192.168.0.10

    agent:
      agent1: 192.168.0.13
      agent2: 192.168.0.15
      agent3: 192.168.0.16
      agent4: 192.168.0.17
      agent5: 192.168.0.18
      agent6: 192.168.0.21

    add-agent:
    gracefully-remove-agent:
    uninstall:

  public:
    # Choice one of your master's public ip
    master: 58.140.91.67:8081
    # Your public node's public ip
    public: 58.140.91.67

# DB part
db:
  ip: 192.168.0.13
  database: uengine
  password: my-secret-pw

# Domain part
host:
  default: pasmini.io
  registry:
    package: darkgodarkgo
    private: gitlab.pasmini.io:5000
    public: gitlab.pasmini.io:5000
  db: db.pasmini.io
  gitlab: gitlab.pasmini.io
  iam: iam.pasmini.io
  eureka-server: eureka-server.pasmini.io
  cloud-server: cloud-server.pasmini.io
  cloud-ui: cloud.pasmini.io
  nexus: nexus.pasmini.io

# Security(IAM) part
iam:
  port: 80
  client-key: my-client-key
  client-secret: my-client-secret
  admin:
    username: admin
    password: admin
  access-token-lifetime: 7200
  mail:
    host: smtp.gmail.com
    username: sppark@uengine.org
    password: !gosu23546
    port: 587
    smtp-auth: true
    smtp-starttls-enable: true
    from-address: sppark@uengine.org
    from-name: uengine

# Mandatory-docker part
mandatory-docker:
  - sppark/uengine-lb:v1
  - mysql:5.7
  - docker:latest
  - node:latest
  - maven:3-jdk-8
  - maven:3-jdk-7
  - sppark/curl-jq:v1
  - openjdk:8u111-jdk-alpine
  - tomcat:7.0.84-jre7
  - webratio/nodejs-http-server
  - google/cadvisor:latest
  - sonatype/nexus:2.14.6-02

# Cloud package part
# Fill out those properties after install DC/OS cluster && Gitlab
# Then, you should re-command "mvn clean install exec:java package"
dcos:
  token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiJkYXJrZ29kYXJrZ29AZ21haWwuY29tIiwiZXhwIjozMTI1NTQ4ODM3MTEuNzkzOX0.NCDPD4HuR8SLMw8T_6lr2QTQ75_E7ppvYIqgaPeWX4s

gitlab:
  root:
    username: root
    password: adminadmin
    token: -arWnfRY7S4h6oyRthNy
  config-repo:
    projectId: 94
    deployment-path: /deployment
    template-path: /template

# Nexus part
nexus:
  ip: 192.168.0.13
  username: admin
  password: admin123
  mvn:
    public: http://nexus.pasmini.io/nexus/content/groups/public/
    release: http://nexus.pasmini.io/nexus/content/repositories/releases/
    snapshot: http://nexus.pasmini.io/nexus/content/repositories/snapshots/
  npm:
    public: http://nexus.pasmini.io/nexus/content/groups/npm/
    private: http://nexus.pasmini.io/nexus/content/repositories/npm-private/

# Pinpoint part
pinpoint:
  use: false
  agent-path:
  web:
  collector:
    ip:
    tcp-port:
    stat-port:
    span-port:

# Elk part
elk:
  elasticsearch:
    private:
    web:
  kibana:
    private:
    web:
    dashboard-id:
      app-log: uengine-app-log
      docker-metric: uengine-doker-metric
      system-metric: Metricbeat-system-overview