# SSH and Resolve.conf part
cluster_name: uEngine
ansible_user: centos
ansible_ssh_private_key_file: /home/centos/belugarKey.pem
ssh_port: 22
resolvers:
- 172.31.0.2
dns_search: ap-northeast-2.compute.internal

# Server list part
server:
  private:
    bootstrap: 172.31.8.143
    gitlab: 172.31.15.249
    ci: 172.31.3.61
    public: 172.31.5.136

    master:
      master1: 172.31.12.143
      master2: 172.31.4.125
      master3: 172.31.1.198

    agent:
      agent1: 172.31.6.35
      agent2: 172.31.1.235
      agent3: 172.31.5.245
      agent4: 172.31.14.247
      agent5: 172.31.7.160
      agent6: 172.31.11.70
      agent7: 172.31.0.164
      agent8: 172.31.10.202
      agent9: 172.31.14.197
      agent10: 172.31.13.131
      agent11: 172.31.1.166
      agent12: 172.31.8.5

    add-agent:
      agent13: 172.31.16.180
      agent14: 172.31.28.163
      agent15: 172.31.17.109
      agent16: 172.31.24.25
      agent17: 172.31.25.39
    gracefully-remove-agent:
    uninstall:

  public:
    # Choice one of your master's public ip
    master: 52.79.125.242
    # Your public node's public ip
    public: 52.79.51.79

# DB part
db:
  ip: 172.31.6.35
  database: uengine
  password: my-secret-pw

# Redis part
redis:
  ip: 172.31.6.35

# Kafka part
kafka:
  private: uengine-kafka.marathon.l4lb.thisdcos.directory:9092
  public: 52.79.51.79:9092

# Domain part
host:
  default: pas-mini.io
  registry:
    package: sppark
    private: gitlab.pas-mini.io:5000
    public: gitlab.pas-mini.io:5000
  db: db.pas-mini.io
  gitlab: gitlab.pas-mini.io
  iam: iam.pas-mini.io
  eureka-server: eureka-server.pas-mini.io
  cloud-server: cloud-server.pas-mini.io
  cloud-ui: cloud.pas-mini.io
  nexus: nexus.pas-mini.io
  redis: redis.pas-mini.io

# Security(IAM) part
iam:
  port: 80
  client-key: my-client-key
  client-secret: my-client-secret
  admin:
    username: admin
    password: admin
  access-token-lifetime: 7200
  mail:
    host: smtp.gmail.com
    username: "sppark@uengine.org"
    password: "!gosu23546"
    port: 587
    smtp-auth: true
    smtp-starttls-enable: true
    from-address: sppark@uengine.org
    from-name: uengine

# Mandatory-docker part
mandatory-docker:
  - sppark/uengine-lb:v1
  - mysql:5.7
  - docker:latest
  - node:latest
  - maven:3-jdk-8
  - maven:3-jdk-7
  - sppark/curl-jq:v1
  - openjdk:8u111-jdk-alpine
  - tomcat:7.0.84-jre7
  - webratio/nodejs-http-server
  - google/cadvisor:latest
  - sonatype/nexus:2.14.6-02

# Cloud package part
# Fill out those properties after install DC/OS cluster && Gitlab
# Then, you should re-command "mvn clean install exec:java package"
dcos:
  token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiJkYXJrZ29kYXJrZ29AZ21haWwuY29tIiwiZXhwIjozMTI1NTU5MDY0MzkuODk0MX0.aHgH_M-g-n-WlnPg_CorMGYEprULPSeUTIGu3GyZQ-U

gitlab:
  root:
    username: root
    password: adminadmin
    token: -arWnfRY7S4h6oyRthNy
  config-repo:
    projectId: 47
    deployment-path: /deployment
    template-path: /template

# Nexus part
nexus:
  ip: 172.31.10.202
  username: admin
  password: admin123
  mvn:
    public: http://nexus.pas-mini.io/nexus/content/groups/public/
    release: http://nexus.pas-mini.io/nexus/content/repositories/releases/
    snapshot: http://nexus.pas-mini.io/nexus/content/repositories/snapshots/
  npm:
    public: http://nexus.pas-mini.io/nexus/content/groups/npm/
    private: http://nexus.pas-mini.io/nexus/content/repositories/npm-private/

# Pinpoint part
pinpoint:
  use: true
  agent-path: /pinpoint-agent
  web: http://pinpoint.pas-mini.io
  collector:
    ip: 172.31.1.228
    tcp-port: 9994
    stat-port: 9995
    span-port: 9996

# Elk part
elk:
  elasticsearch:
    private: 172.31.11.218:9200
    web: http://13.125.185.128:9200
  kibana:
    private: 172.31.11.218:5601
    web: http://13.125.185.128:5601
    dashboard-id:
      app-log: uengine-app-log
      docker-metric: uengine-doker-metric
      system-metric: Metricbeat-system-overview