title: 
server.public.master: 52.79.125.242
server.public.public: 52.79.51.79

db.ip: 172.31.6.35
db.database: uengine
db.password: my-secret-pw

redis.ip: 172.31.6.35

host.default: pas-mini.io
host.registry.package: sppark
host.registry.private: gitlab.pas-mini.io:5000
host.registry.public: gitlab.pas-mini.io:5000
host.db: db.pas-mini.io
host.gitlab: gitlab.pas-mini.io
host.iam: iam.pas-mini.io
host.config: 172.31.5.136:10000
host.eureka-server: eureka-server.pas-mini.io
host.cloud-server: cloud-server.pas-mini.io
host.cloud-ui: cloud.pas-mini.io
host.nexus: nexus.pas-mini.io
host.redis: redis.pas-mini.io

iam.port: 80
iam.client-key: my-client-key
iam.client-secret: my-client-secret
iam.admin.username: admin
iam.admin.password: admin
iam.access-token-lifetime: 7200
iam.mail.host: smtp.gmail.com
iam.mail.username: sppark@uengine.org
iam.mail.password: !gosu23546
iam.mail.port: 587
iam.mail.smtp-auth: true
iam.mail.smtp-starttls-enable: true
iam.mail.from-address: sppark@uengine.org
iam.mail.from-name: uengine

dcos.token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiJkYXJrZ29kYXJrZ29AZ21haWwuY29tIiwiZXhwIjozMTI1NTU5MDY0MzkuODk0MX0.aHgH_M-g-n-WlnPg_CorMGYEprULPSeUTIGu3GyZQ-U

gitlab.root.username: root
gitlab.root.password: adminadmin
gitlab.root.token: -arWnfRY7S4h6oyRthNy
gitlab.config-repo.projectId: 47
gitlab.config-repo.deployment-path: /deployment
gitlab.config-repo.template-path: /template

kafka.private: 172.31.5.136:9092
kafka.public: 52.79.51.79:9093

nexus.ip: 172.31.10.202
nexus.username: admin
nexus.password: admin123
nexus.mvn.public: http://nexus.pas-mini.io/nexus/content/groups/public/
nexus.mvn.release: http://nexus.pas-mini.io/nexus/content/repositories/releases/
nexus.mvn.snapshot: http://nexus.pas-mini.io/nexus/content/repositories/snapshots/
nexus.npm.public: http://nexus.pas-mini.io/nexus/content/groups/npm/
nexus.npm.private: http://nexus.pas-mini.io/nexus/content/repositories/npm-private/

pinpoint.use: true
pinpoint.agent-path: /pinpoint-agent
pinpoint.web: http://pinpoint.pas-mini.io
pinpoint.collector.ip: 172.31.1.228
pinpoint.collector.tcp-port: 9994
pinpoint.collector.stat-port: 9995
pinpoint.collector.span-port: 9996

elk.elasticsearch.private: 172.31.11.218:9200
elk.elasticsearch.web: http://13.125.185.128:9200
elk.kibana.private: 172.31.11.218:5601
elk.kibana.web: http://13.125.185.128:5601
elk.kibana.dashboard-id.app-log: uengine-app-log
elk.kibana.dashboard-id.docker-metric: uengine-doker-metric
elk.kibana.dashboard-id.system-metric: Metricbeat-system-overview








