---
# Sample Zuul configuration

spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: 52.79.164.208:9092
      bindings:
        billing-sub:
          group: ${spring.application.name}
          destination: billing
        metering-pub:
          destination: metering

zuul:
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  addProxyHeaders: true

  # Decides to check the token.
  iam-authentication: true

  # Key to determine if the token's signature is correct.
  # It must be the same key that IAM used to issue the token.
  # Copy and paste from your IAM's iam.jwt.key
  iam-jwt-key: my-jwt-encrypt-key-my-jwt-encrypt-key

  # 메타데이터 암호화 키
  metadata-encoder-secret1: Bar12345Bar12345
  metadata-encoder-secret2: ThisIsASecretKet

  # 복호화 할 메타데이터 필드.
  secure-metadata-fields:
    - "$.gitlabToken"

  billing:
    enable: false
    url: "http://billing.pas-mini.io"
    authentication: "Basic YmlsbGluZ0B1ZW5naW5lLm9yZzoxODkyNXVuZw=="
    organization: "562980b6-9ad6-4257-b276-a38825522f69"

  routes:
    order:
      path: /orders/**
      serviceId: order-service
      stripPrefix: false
      # List of scopes needed for this path
      iam-scopes:
        - guest/GET
        - catalog-order/PUT-PATCH-POST-DELETE

    # If no iam-scopes, all request will be passed.
    customer:
      path: /customers/**
      serviceId: customer-service
      stripPrefix: false


    item:
      path: /items/**
      serviceId: order-service
      stripPrefix: false
      iam-scopes:
        - guest/GET
        - catalog-manage/PUT-PATCH-POST-DELETE

  ratelimit:
    key-prefix: your-prefix
    enabled: true
    repository: IN_MEMORY
    behind-proxy: true
    default-policy-list: #optional - will apply unless specific policy exists
      - limit: 10 #optional - request number limit per refresh interval window
        quota: 1000 #optional - request time limit per refresh interval window (in seconds)
        refresh-interval: 60 #default value (in seconds)
        type: #optional
          - user
          - origin
          - url
    policy-list:
      definition:
        - limit: 5 #optional - request number limit per refresh interval window
          quota: 1000 #optional - request time limit per refresh interval window (in seconds)
          refresh-interval: 60 #default value (in seconds)
          type: #optional
            - user
            - origin
            - url
      definition2:
        - limit: 10 #optional - request number limit per refresh interval window
          quota: 1000 #optional - request time limit per refresh interval window (in seconds)
          refresh-interval: 60 #default value (in seconds)
          type: #optional
            - user
            - origin
            - url